/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WpbmvS081Ro
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { type ReactNode } from "react"

export function HomeLayout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col justify-between min-h-screen">
      <header className="flex h-20 w-full items-center px-4 md:px-6">
        <Link
          className="mr-6 hidden lg:flex transform hover:scale-110 transition-transform duration-300 items-center"
          href="#"
        >
          <GemIcon className="h-6 w-6" />
          <span className="text-2xl font-bold ml-2 align-middle">Kyanite Nepal</span>
        </Link>
        <nav className="flex flex-grow justify-center space-x-4">
          <Link
            className="text-lg hover:underline transform hover:scale-110 transition-transform duration-300"
            href="#"
          >
            Collection
          </Link>
          <Link
            className="text-lg hover:underline transform hover:scale-110 transition-transform duration-300"
            href="#"
          >
            About Us
          </Link>
          <Link
            className="text-lg hover:underline transform hover:scale-110 transition-transform duration-300"
            href="#"
          >
            Blog
          </Link>
        </nav>
        <Button className="ml-auto transform hover:scale-110 transition-transform duration-300" variant="outline">
          Shop Now
        </Button>
      </header>
      {children}
      <footer className="flex h-14 items-center justify-center border-t">
        <p className="text-sm text-gray-600">© Nepal Kyanite. All rights reserved.</p>
      </footer>
    </div>
  )
}

function GemIcon(props: { className: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 3h12l4 6-10 13L2 9Z" />
      <path d="M11 3 8 9l4 13 4-13-3-6" />
      <path d="M2 9h20" />
    </svg>
  )
}
